version: '3.7'

services:
  api:
    container_name: dockerizacao_api
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - ${API_PORT}:${API_PORT}
    env_file:
      - .env
    networks:
      - docker-network
    depends_on:
      - postgres
  postgres:
    container_name: dockerizacao_db
    image: postgres:13-alpine 
    networks:
      - docker-network
    environment:
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_DB: ${TYPEORM_DATABASE}
    ports:
      - ${TYPEORM_PORT}:${TYPEORM_PORT}
networks:
  docker-network: